### ISSUE TITLE
Remove obsolete branches

### ISSUE THREAD

**Issue by dregad** [getopt-php/getopt-php#107]
I noticed there are several feature branches in the repo that have been merged to master, is there any particular reason for keeping them in ? If not, I would suggest deleting them

``` console
$ git branch --remote --merged master |grep -Ev "master|HEAD"
  origin/2.x
  origin/fix-iterator
  origin/fix-requiredOperands
  origin/fix-unknownOperands
  origin/getters
  origin/oop-help
  origin/update-documentation
```

**Comment by tflori** [comment]
of course, except 2.x they can be removed

**Comment by tflori** [comment]
done
