### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by Arcesilas** [getopt-php/getopt-php#114]
Hi,

According to https://secure.php.net/supported-versions.php and https://secure.php.net/eol.php PHP 5.4 is dead since 2 years and 7 months and 5.5 since 1 year, 8 months.

Concerning 5.6 and 7.0, they only get security fixes and until the end of this year only.

At the same time, PHPUnit 4.8 is no longer supported, as for PHPUnit 5 for 2 months.
PHPUnit 6, which is the oldest version supported (for 1 year from now) only supports PHP >= 7.0

Maybe it could be worth considering dropping PHP 5.x versions and upgrading dependencies...?
A branch for a future version 4 release could be started, which would support PHP >= 7.1 (with PHPUnit 7 and PHP CS 3.2) ?
When possible, features could be backported to 3.x (for PHP 5.4 - 5.6), which branch would still be supported for a while, even when 4.0 will be released.

What do you think?

Note: I have some free time...

**Comment by tflori** [comment]
I also would prefer to just write for php 5.6 and 7.x - even debian stable has now php 7.0. I would prefer to stay with php 7.0 support at least.

Of course we should then also update the dependencies (phpunit, phpcs and so on).

**Comment by dregad** [comment]
Just my 2 cents... I believe that it is important for a library such as getopt-php to remain compatible with older versions when (and as long as) possible. 

Consider that corporate environments may not have the option to run the latest & greatest (I know companies which still run apps on PHP 5.3 and even 5.2 :fearful:), and some distros are still packaging older PHP, e.g. CentOS 7 has PHP 5.4.

Bottomline, unless we actually absolutely *need* a specific new language feature, I think it's better to be conservative about this. As long as the code does work with newer versions of the software, we're good. And IMHO PHPUnit support is not an argument (unless we face an actual bug, which I think would be unlikely)

**Comment by Arcesilas** [comment]
I'm perfectly aware that companies sometimes use very old very old versions of PHP (I'm pretty sure there are also some very old apps in PHP 4 somewhere).

My proposition was not to stop supporting old versions of PHP, but to start a new branch for a new version (4.0) which would support PHP 7+. Old version (3.x) would still be supported and features would be backported when possible.

The idea behind this is to encourage the use of newer versions. I consider this is also the role of every package developper to take consider this question. For now, we may not see the profit of the use of new language features from PHP7+. But later some changes will probably not be able to be backported to version for PHP 5.x.

That's the cycle of life of software: new versions bring more feature, while older ones may still work.

**Comment by tflori** [comment]
Yes, that's a good point. But in my opinion they also don't need new features and can stick with old versions.

We still have branch 2.x for bugfixes.

**Comment by ycgambo** [comment]
remain compatible with older versions

The security thing is important to package user, not the provider

This is a tool, not a chain

**Comment by AnrDaemon** [comment]
Is there any harm in supporting PHP 5.3?
Is there any good missing in not enforcing PHP7+ ?
No? Then I see no reason to bother.
Once PHP5 is entirely out of support, you can begin to rely on 7+ features unconditionally.
