### ISSUE TITLE
Can I getopt from a string other than cli

### ISSUE THREAD

**Issue by ycgambo** [getopt-php/getopt-php#122]
I have an app read line text from client
I want to parse option from line input but there has no package can do this

**Comment by tflori** [comment]
Yes, you can. You can just use `$getOpt->parse($string)`.

**Comment by tflori** [comment]
Ah sorry the method is called process:

https://github.com/getopt-php/getopt-php/blob/master/test/GetoptTest.php

Here are some examples...

**Comment by ycgambo** [comment]
thanks a lot, exactly what i want
