### ISSUE TITLE
Option X has an invalid value

### ISSUE THREAD

**Issue by udf2457** [getopt-php/getopt-php#123]
GetOpt 3.0.0 on PHP 7.2.4

Looking through the docs I'm not quite sure where I'm going wrong here ?

Given:
```
    public function __construct() {
        parent::__construct('foobar', [$this, 'handle']);
        $this->addOptions([
            Option::create('b','barfoo', GetOpt::REQUIRED_ARGUMENT)
                ->setValidation('is_writable')
        ]);
    }
```
Surely one would expect `php main.php foobar -b /tmp/foo` or `php main.php foobar -b "/tmp/foo"` to work ?

But I am getting `Option 'barfoo' has an invalid value`

The `/tmp` directory is obviously writable and the suggested file `/tmp/foo` does not exist.

**Comment by tflori** [comment]
Btw. the problem is not within getopt or the documentation. It is phps is_wtriteable function that is not working as you expected.

**Comment by udf2457** [comment]
Fair enough.  So a side question, what's the correct way to drop out of a failed command ?

e.g. I've put the above directory testing into a class, and the constructor is as follows:
```
    public function __construct ($fileName) {
        if (!\is_writeable(\dirname($fileName))) { return false; }
        if (!$this->fileHandle=\fopen($fileName,'xb')) { return false; }
    }
```

I've then got:
```
public function handle(GetOpt $getOpt) {
if (!$fileWriter=new FileWriter($getOpt->getOption('p'))) { throw new \Exception("e");  }
```

However it does not seem to matter if `throw` or `return false` in the `handle()`, `GetOpt` seems to continue parsing what's below the `if()` test despite the `if()` failing.

**Comment by tflori** [comment]
You can return what ever you want in a constructor the value returned from `new Something()` is always an object of Something.

I think you need to throw in the constructor to get what you want.
