### ISSUE TITLE
Infinite loop with long strings in help messages

### ISSUE THREAD

**Issue by lorman** [getopt-php/getopt-php#127]
There is an error that causes an infinite loop and memory leak when asked to display a help message with a long string without spaces to split on.

This is in [Help.php Line:321](https://github.com/getopt-php/getopt-php/blob/master/src/Help.php#L321). 

The fix was to check if `$p` is less then the padding `$columnWidth + 3`.

So adding this fixed the issue:
```
if ($p <= $columnWidth+3) $p = mb_strlen($row);
```

**Comment by tflori** [comment]
yes, when I developed it I thought "a text never consists of words longer than the available space". I don't want to discuss this so you will have a too long description instead of an endless loop in the next release.

**Comment by tflori** [comment]
this is solved with #128 and in version 3.1.2
