### ISSUE TITLE
GetOptions only shows a number, not the option value

### ISSUE THREAD

**Issue by paulcanning** [getopt-php/getopt-php#137]
When I dump `$getOpt->getOptions()` all I get is an array containing numbers, not the value passed.

EG

`php index.php --version "Test"` gives me

```
array (
  'v' => 1,
  'version' => 1,
)
```

**Comment by tflori** [comment]
When the option has no argument you get the count. That's helpful for example when you have a verbose option: ‘-v‘ verbosity 1 and ‘-vv‘ verbosity 2...
