### ISSUE TITLE
Cannot figure out operands at all

### ISSUE THREAD

**Issue by paulcanning** [getopt-php/getopt-php#138]
I'm really struggling with the operands.

I assume they are there so that specific options are needed, but the documentation makes zero sense to me.

Here is my code

```
$fileOption = new Option('f', 'file', \GetOpt\GetOpt::REQUIRED_ARGUMENT);
$convertedFileOption = new Option('c', 'converted', \GetOpt\GetOpt::REQUIRED_ARGUMENT);

$getOpt = new GetOpt();
$getOpt->addOptions([$fileOption, $convertedFileOption]);
$getOpt->addOperand(\GetOpt\Operand::create('file', \GetOpt\Operand::REQUIRED));
$getOpt->addOperand(\GetOpt\Operand::create('converted', \GetOpt\Operand::REQUIRED));
$getOpt->process();

var_export($getOpt->getOperands());
```

If i  enter `php index.php --file=test.csv` I get the error:

```
PHP Fatal error:  Uncaught GetOpt\ArgumentException\Missing: Operand file is required in /Users/me/demo/vendor/ulrichsg/getopt-php/src/GetOpt.php:197
```

**Comment by tflori** [comment]
You have both, an option and an operand. When you output the help you will see what you have created. The argument of the option already exists when you add the option. You could also say that an option is a named operand.

**Comment by paulcanning** [comment]
Sorry but that makes less sense than the documentation.

Basically, how can I force an option to be required (not a required value, but a required OPTION)

**Comment by tflori** [comment]
Not at all. You can only have required arguments and required operands. It the usual behavior

**Comment by tflori** [comment]
is this solved now? if not feel free to reopen...
