### ISSUE TITLE
Allow option of permitting extra command line options that haven't been defined in Getopt

### ISSUE THREAD

**Issue by rightaway** [getopt-php/getopt-php#14]
If I parse command line options and one of the options haven't been defined in Getopt (by doing addOption), there's an error because of the undefined option. I'd like to use Getopt in some code where the expected command-line options are defined dynamically and not always known up front. It would be great to have an option that allows for extra options on the command-line that haven't been defined. Such an option could be passed in when instantiating the Getopt object.

**Comment by tflori** [comment]
the same issue we have vise versa with operands. Someone may want to limit the operands to what he defined when he can define the operands what is part of #27.

I'm thinking to have two similar settings `SETTING_STRICT_OPTIONS` (default `true`) and `SETTING_STRICT_OPERANDS` (default ` false)
