### ISSUE TITLE
getOptions returns duplicates

### ISSUE THREAD

**Issue by npelov** [getopt-php/getopt-php#141]
getOptions() returns both short and long options. In my opinion this should work like the iterator, because if you want to iterate them the options will be duplicated:

```
foreach($options as $option=>$value){
  // .. do stuff
}
```

Technically if you want option by name you wouldn't fetch array. you would use getOption() for that.

Optionally you could have additional method getAllOptions() to include short + long when both available.

**Comment by tflori** [comment]
I must admit this is something I also was not happy about but on the other hand: when you get all options you check for an option with the name `$options['help']` or `$options['h']` and not via iterate and switch like in gnus getopt. When you really want to iterate use iterator - that''s the reason for the iterator. And if you really want to have only long options:

```php
$options = iterator_to_array($getopt->getInterator());
```

**Comment by tflori** [comment]
I'm guessing this is solved since there was no answer for 3 weeks.
