### ISSUE TITLE
Version 3.3

### ISSUE THREAD

**Issue by tflori** [getopt-php/getopt-php#151]
There is a new release candidate (3.3.0-rc.1) that wants to be tested. I tried it on my project and it works.. Maybe some others have experienced bugs because of changes?

https://github.com/getopt-php/getopt-php/releases/tag/v3.3.0-rc.1

I appreciate any comments.

**Comment by vicchi** [comment]
@tflori Upgraded my Composer dependencies to pull in `v3.3.0-rc.1` this morning as a result of upgrading to PHP `7.4.0`. No errors, bugs or unexpected behaviour in this release candidate so far.

**Comment by tflori** [comment]
ok, then lets release it... have fun :)
