### ISSUE TITLE
Add option to validate default value

### ISSUE THREAD

**Issue by orklah** [getopt-php/getopt-php#156]
Hi,

It would be cool if it was possible to set an option when using setValidation on an option to allow validating the default value.

I need this because I expect a path in an option. However, I have a default name file that i can accept, even if it's not explicitly passed in the option. I put the default path in the defautValue, but the validator is not called so I can't check if the file is really there.

Thanks

**Comment by tflori** [comment]
I'm not sure if I understood correctly why you need this. Can you show a small example or could this help you:

```php
$option = Option::create('c', 'config', GetOpt::REQUIRED_ARGUMENT)
    ->setValidation('file_exists')
    ->setValue('/path/to/default/config');
$getOpt->addOption($option);
```

The getopt instance does not handle default values different - it just calls `$option->getValue()` where the value is coming from is irrelevant. You can call `$option->setValue()` multiple times.

**Comment by orklah** [comment]
Hi,

Thanks for your answer.

I didn't saw the setValue method in docs, however I'm not sure if it's the right tool.

My code is:
```php
$configOption = new Option('c', 'config', GetOpt::OPTIONAL_ARGUMENT);
$configOption->setDescription('-c or --config followed by the path of the config file');
$configOption->setDefaultValue(PATH.DIRECTORY_SEPARATOR.'default.json');
$configOption->setValidation(
    static function ($path) {
        return is_file($path);
    }
);
```

When -c on --config is passed, everything is ok, but when it's not passed, the option takes the default value but the setValidation callback is not called.

The effect is that I get a path, I get the value I expected but I'm not sure if the file actually exists. I have to check again and that defeats the entire purpose of the setValidation callback in this case.

I guess I could have a dynamic defaultValue depending if the file exists or not but it seems weird.

**Comment by orklah** [comment]
Is this something that would suit this package? If so, I can try to submit a PR? If not, this issue can be closed.

Thanks!

**Comment by tflori** [comment]
Validation is not happening in `Argument::getValue()` but in `Argument::setValue()`. Maybe `Argument::setDefaultValue` could have validation - I don't see a reason why not.. we even don't need an option:

```php
// will not validate the default value because the validation is not defined yet:
$option = Option::create('c', 'config')
    ->setDefaultValue(getcwd().'/default.json')
    ->setValidation('is_file');

// will validate the default value
$option = Option::create('c', 'config')
    ->setValidation('is_file')
    ->setDefaultValue(getcwd().'/default.json');
```

If you prepare a PR for that.. why not

**Comment by orklah** [comment]
Hi! Thanks for the answer! I'm not working on that project anymore though and I don't expect to in the near future so I'll close this.

However, I must admit I'd be quite disturbed as a user by a fluent interface if the order of the methods *sometimes* have an impact on the execution.

I'd have preferred an option or even a second parameter to the setValidation callback to know if the value comes from default.
