### ISSUE TITLE
Option with missing REQUIRED_ARGUMENT consumes next option?

### ISSUE THREAD

**Issue by vicchi** [getopt-php/getopt-php#160]
With the caveat that it's entirely possible that I'm mis-reading the documentation ...

If an option with a required argument is missing that argument, the next option appears to be consumed as the "missing" argument's value.

A test case will probably make this clearer (PHP 7.4.3 via Homebrew, `getopt-php` 3.3, macOS 10.15.3) ...

```php
#!/usr/bin/env php
<?php

require_once dirname(__FILE__) . '/vendor/autoload.php';

use GetOpt\GetOpt;
use GetOpt\ArgumentException;
use GetOpt\ArgumentException\Missing;

$getopt = new GetOpt([
    ['?', 'help', GetOpt::NO_ARGUMENT, 'Display this help text'],
    ['m', 'manifest', GetOpt::REQUIRED_ARGUMENT, 'Path to JSON manifest file'],
    ['d', 'data-tag', GetOpt::REQUIRED_ARGUMENT, 'Reference Data source tag'],
    ['l', 'latest-release', GetOpt::NO_ARGUMENT, 'Get the latest release tag; requires -d'],
    ['L', 'list-releases', GetOpt::NO_ARGUMENT, 'List all release tags; requires -d'],
    ['r', 'release', GetOpt::REQUIRED_ARGUMENT, 'Get a specific release tag; requires -d']
]);
$getopt->getOption('manifest', true)->setArgumentName('manifest-file');
$getopt->getOption('data-tag', true)->setArgumentName('data-tag');
$getopt->getOption('release', true)->setArgumentName('release-tag');

try {
    try {
        $getopt->process();
    }
    catch (Missing $e) {
        if (!$getopt->getOption('help')) {
            throw $e;
        }
    }
}
catch (ArgumentException $e) {
    fwrite(STDERR, $e->getMessage() . PHP_EOL);
    echo PHP_EOL . $getopt->getHelpText();
    exit;
}

if ($getopt->getOption('help')) {
    echo $getopt->getHelpText();
    exit;
}

$options = $getopt->getOptions();
var_dump($options);
```

If I then run this script as `./test.php -d -l`, my expected behaviour is for a `GetOpt\ArgumentException\Missing` exception to be thrown. However what seems to be happening is that `-l` is consumed as the (missing) argument for `-d`, as seen in the output of `var_dump` below.

```
./test.php -d -l
array(2) {
  ["d"]=>
  string(2) "-l"
  ["data-tag"]=>
  string(2) "-l"
}
```

The implication is that this is positional dependent, thus running `./test.php -l -d` yields the expected behaviour ...

```
./test.php -l -d
Option 'data-tag' must have a value

Usage: ./test.php [options] [operands]

Options:
  -?, --help                      Display this help text
  -m, --manifest <manifest-file>  Path to JSON manifest file
  -d, --data-tag <data-tag>       Reference Data source tag
  -l, --latest-release            Get the latest release tag; requires -d
  -L, --list-releases             List all release tags; requires -d
  -r, --release <release-tag>     Get a specific release tag; requires -d
```

Am I missing something in the documentation or is this _as expected_ but with a workaround/resolution I haven't worked out yet? 

On a related note, I'm wondering if this is somehow connected to #136 and #139?

**Comment by tflori** [comment]
This is indeed the expected behavior. I just tried it with grep for example:

```console
$ echo "Hello world -a"|grep -e -a
Hello world -a
```

But:

```console
$ echo "Hello world -a"|grep -o -a
Usage: grep [OPTION]... PATTERNS [FILE]...
```

Because `-e` requires an argument `-a` gets the argument instead of the option `-a`.

**Comment by vicchi** [comment]
@tflori Just filed that mentally under _things I didn't know but probably should have_. Thanks for the reply and the clarification.

And of course, massive thanks to yourself, to @ulrichsg and all the contributors for an insanely useful library that I find myself using more and more with each passing tool I write.
