### ISSUE TITLE
Cleaning up merged branches

### ISSUE THREAD

**Issue by dregad** [getopt-php/getopt-php#167]
Hello Thomas,

FYI I just noticed there's a number of branches left around in the repo after the corresponding PRs were merged. 

I have removed them, using the following command-line:
```bash
git branch --format=":%(refname:lstrip=3)" --remote --merged origin/master | 
  egrep -v "^:(master|HEAD|[[:digit:]]+\.x)" |
  xargs git push origin
```
```
To github.com:getopt-php/getopt-php.git
 - [deleted]         docs32
 - [deleted]         feature-operand-descriptions
 - [deleted]         feature/commands-with-spaces
 - [deleted]         feature/validation-message
 - [deleted]         issue-134
 - [deleted]         issue-136
```

**Comment by dregad** [comment]
I guess _2.x_ and _3.1_ could be deleted as well, but I thought you might want to make that a conscious decision. 

I'm not sure what the _v3_ branch is about - seems like a work-in-progress effort that went nowhere.

**Comment by tflori** [comment]
thx for cleaning that up. yes the v3 branch was from Ulrich some years ago. I don't think it is still planned to do something with that code but I don't want to remove it - at the end it is just a link to the last commit in that branch.

**Comment by dregad** [comment]
Fine with me. Feel free to close this if you think the needed work is done.
