### ISSUE TITLE
Outdated CHANGELOG.md file

### ISSUE THREAD

**Issue by dregad** [getopt-php/getopt-php#168]
The [Changelog](https://github.com/getopt-php/getopt-php/blob/master/CHANGELOG.md) stops at 3.0.0 alpha.

**Comment by tflori** [comment]
I haven't updated the changelog anymore. Instead I'm using the release informations as changelog. Therefore you can find the changelog after 3.0 here: https://github.com/getopt-php/getopt-php/releases

We could either link it in the file or update it if you think it should be there too.

**Comment by dregad** [comment]
> I'm using the release informations as changelog

I found it there of course. And that's fine, it's just that I had a local checkout of the repo, and after pulling the latest changes I looked at changelog and was surprised not to find anything new there.

I don't really need the info duplicated there, but it would be nice to redirect people with a note at the top of the file stating something like 
```
Please find Changelog information for releases 3.0 and later on GitHub 
https://github.com/getopt-php/getopt-php/releases
```

**Comment by tflori** [comment]
I've added the link. Thanks for that hint
