### ISSUE TITLE
What are the version constraints?

### ISSUE THREAD

**Issue by njt1982** [getopt-php/getopt-php#170]
https://github.com/getopt-php/getopt-php/blob/073e809a5a4811b0caec43a2151b0e8ccbe29e4b/composer.json#L4

vs

https://github.com/getopt-php/getopt-php/blob/073e809a5a4811b0caec43a2151b0e8ccbe29e4b/composer.json#L18

It looks like 7.4 is compatible?

**Comment by tflori** [comment]
Omg. Thx will fix it tomorrow. It is compatible with php7 >= 7.1.0 and php8

**Comment by njt1982** [comment]
Awesomesauce! So far, it's a nice tool!

**Comment by dregad** [comment]
This was fixed in eb621806c1cef18cad88c66dc21fbe860f30ca01
