### ISSUE TITLE
Error on PHP 8.1.0

### ISSUE THREAD

**Issue by jonasraoni** [getopt-php/getopt-php#171]
After bumping my PHP to 8.1.0 I started receiving such issues (after fixing the file manually, everything worked fine)

```php
During inheritance of ArrayAccess: Uncaught Exception:
Return type of GetOpt\GetOpt::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed,
or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at \ulrichsg\getopt-php\src\GetOpt.php:505
```

**Comment by tflori** [comment]
:laughing: these php dudes are funny!

lets fuck up every library that is implementing array access and implement `#[\ReturnTypeWillChange]`. Anyway we have to go with that if we want (yes, we do want) to be compatible to php 7.

I'm fine with a MR with that comment

**Comment by jonasraoni** [comment]
@tflori Try to imagine the impact of this one https://wiki.php.net/rfc/deprecate_dynamic_properties when it hit some old codes 💣

I've created the PR: https://github.com/getopt-php/getopt-php/pull/173 =]
