### ISSUE TITLE
Failed Operand validation should throw non-zero exit code

### ISSUE THREAD

**Issue by SuperFamousGuy** [getopt-php/getopt-php#174]
I've created an operand like such:
```
    $this->addOperand(
            Operand::create(self::SERVERS_OPERAND, Operand::REQUIRED | Operand::MULTIPLE)
                ->setDescription('The list of servers to connect to.')
                ->setValidation(
                    function ($server) {
                        return in_array($server, $this->getFilteredServerList(), true);
                    }
                )
                ->multiple()
        );
```

Which works as expected, but when the validation fails it is still throwing a 0 exit code. This is particularly problematic when trying to use this script in Jenkins where the user provides the server via an input. When an invalid value is provided the job still passes.

```
$ php common:ssh:exec -u superfamousguy -i ~/.ssh/id_rsa 'ls' aalkjlkdjf
Operand 'servers' has an invalid value
$ echo $?
0
```

**Comment by SuperFamousGuy** [comment]
Nevermind, I'm dumb sometimes. I found the place in my code that was catching the Invalid exception and returning a 0 exit code.

**Comment by tflori** [comment]
no worries :slightly_smiling_face: 
nice to see that the multiple operand thing is actually used :+1:
