### ISSUE TITLE
Customizable usage message / operand specification

### ISSUE THREAD

**Issue by morozov** [getopt-php/getopt-php#27]
For a CLI application with fixed set of operands it'd be useful if it was possible to describe them explicitly in "usage" message. I.e. instead of

```
Usage: copy [options] [operands]
Options:
  --overwrite             Overwrite existing file
```

I'd like to have a more meaningful message like

```
Usage: copy [options] <from> <to> [<optional-operand>]
Options:
  --overwrite             Overwrite existing file
```

In fact, this example brings the idea of operands specification alongside with the one for options. Like options, operands may also have names, be mandatory or optional and have default values.

**Comment by tflori** [comment]
with #75 you will be able to define from and to very easy:

```php
$getopt = new Getopt();
$getopt->addOperand(new Operand('from'));
$getopt->addOperand(new Operand('to'));

echo $getopt->getHelpText();
```

If you want to try it by yourself you can install `3.0.x-dev` or `dev-feature-operandSpecification`

**Comment by morozov** [comment]
@tflori thank you. I'm currently not working on the project I was asking this for (it's been 3½ years since then). I'll give it a try once I start working on something similar.
