### ISSUE TITLE
Explicit Options

### ISSUE THREAD

**Issue by patinthehat** [getopt-php/getopt-php#31]
I'd like to see a way to enable explicit options, meaning either option "x" can be passed as an option, but option "y" would not be allowed or vice-versa (with one possibly being the default).  
A real-world example might be:
`script.php --read myfile.txt`
<i>or</i>
`script.php --write myfile.txt "test data"`
The idea is that both options cannot coexist ahd either an Exception would be thrown or it would default to one.
It could even be expanded to multiple arguments or operands.

Any thoughts?

**Comment by patinthehat** [comment]
@ulrichsg it has been some time since we discussed this issue.  I am still interested in implementing mutually exclusive --flags, i.e. `-a OR -b but NOT -a AND -b`. 
I feel that this is fundamentally different from command-type implementation referenced in #29.

I can create a branch to this effect and we can see where it goes from there unless you have decided against this feature.

**Comment by fernandopsilveira** [comment]
It would be great if getHelpText method could deliver separate sections for commands, options and fixed operands; even better if they could get different paddings.

**Comment by tflori** [comment]
As I'm now maintaining this project I'm thinking of implementing the functionality from tflori/commands to version 3.

**Comment by tflori** [comment]
@patinthehat For explict options I'm not sure how to implement it. #41 will be in version 3 for sure.

You can already implement explict options in version 3:
```php
$getopt = new Getopt;

$optionA = new Option('a');
$optionA->setArgument(new Argument(null, function ($value) use ($getopt) {
  return empty($getopt->getOption('b'));
}));
$getopt->addOption($optionA);

$optionB = new Option('b');
$optionB->setArgument(new Argument(null, function ($value) use ($getopt) {
  return empty($getopt->getOption('a'));
}));
$getopt->addOption($optionB);

// I hope I closed all braces and parenthesis
```

This way option a can not be given when option b is given and vise versa.

```php
// these will throw an exception
$getopt->process('-a -b');
$getopt->process('-b -a');
```

**Comment by tflori** [comment]
ahh sorry - that is currently not true for options without arguments. Without argument the test will not be executed and `setArgument` throws an error when the mode is `NO_ARGUMENT`.

**Comment by tflori** [comment]
@patinthehat I changed the ordering and executing the validation now also for NO_ARGUMENT options.

Now it is possible to check for explicit options. For options with NO_ARGUMENT you have to use `setValidation()` instead of `setArgument()`. Example in the `ArgumentsTest`.

If this is ok for you, I will close this ticket now?
