### ISSUE TITLE
Getopt::getScriptName method

### ISSUE THREAD

**Issue by acim** [getopt-php/getopt-php#53]
It would be useful to have this method in order to find out the script name outside of Getopt class. For example to be able to show the script version number (including script name) and without using $argv.

**Comment by AnrDaemon** [comment]
Do note that "script name" is not known until you ->parse(). And there's is a reason behind it.
Imagine something like this synopsis:
```
route add [-m <method>] [-{p|r|e|s} <route>] <dispatcher>
route del {--id <id> | --reset}
route dump [--export]
```
Now, when you parse, your "script name" will either be the command (add, del, etc.), or script name+command. Depends, how would you go about it.

**Comment by AnrDaemon** [comment]
Actually, no. Getopt::parse($customArray) doesn't set Getopt::scriptName at all.
And there's no way to provide it, short of writing it explicit in the synopsis.

**Comment by tflori** [comment]
this projects seems to be dead. no pull requests accepted since June 2015. I forked this project to tflori/getopt-php. I would accept such a pull request there.

There you also have the ability to set the scriptname by self:

```php
$getopt = new Getopt('a');
$getopt->setScriptName('/usr/local/bin/myscript');
```

It is usually not necessary in this version - cause it uses argv[0] anyway - even if you pass arguments. In your case this might be more helpful:

```php

$getopt = new Getopt();

if (in_array('--version', $_SERVER['argv'])) {
  $getopt->parse([]);
  echo $getopt->getScriptName() . " version 2.1\n";
} else {
  $getopt->addOptions([]);
  $getopt->parse();
}
```

**Comment by ulrichsg** [comment]
@tflori: If you'd like to take over maintaining this project, I'd be happy to put a link to your repo on this one. Just let me know it that's ok with you.

**Comment by tflori** [comment]
@ulrichsg yes I'm fine with it

**Comment by tflori** [comment]
@acim If you are still interested: there is now a setter for script name and you don't have to parse before. there is still no setter but if you want to add one I'm fine with it and we can put it to 2.4.3

P.S. how small the world is. I just realized its you :smile:

**Comment by acim** [comment]
Hi Thomas, yes, the world is definitely small :) Thank you for this but at the moment I do not use this, it was at my previous employer Planet Sports. See you ;)
