### ISSUE TITLE
remove support for php 5.3

### ISSUE THREAD

**Issue by tflori** [getopt-php/getopt-php#72]
I know some years ago php 5.3 was alive but even the latest debian stable has now php 7 and I'm wondering if we still need php 5.3 support.

php 5.3 is not supported by zend since almost 3 years. it's not only about short array syntax and using $this in a closure. there is also no `callable` type for parameters.

the nicest would be to ask everyone who is using this lib but I don't see a way for this. from packagist statistics it looks like 5.3 is still supported by a lot of packages but almost no one is using it:
https://seld.be/notes/php-versions-stats-2017-1-edition

@ulrichsg what do you think?

**Comment by tflori** [comment]
this really looks ugly and is very annoying for me:
https://github.com/getopt-php/getopt-php/commits/feature-commands

**Comment by ulrichsg** [comment]
I'm all for it. :+1:
