### ISSUE TITLE
remove wrong versions

### ISSUE THREAD

**Issue by tflori** [getopt-php/getopt-php#77]
Hey Ulrich, sorry to bother you. 

I have mistakenly released a tag 3.0.0-alpha.2 on master instead of branch 3.0. Because I'm not owner of the package on packagist I cant delete version. Can you please remove version `3.0-alpha.1` and `3.0.0-alpha.2` from packagist?

Thanks!

**Comment by ulrichsg** [comment]
No problem. They're gone :)

**Comment by tflori** [comment]
Oops I did it again. I created again an alpha version 3.0.0-alpha.5 on master :(

I fixed it already but composer still installes the wrong version.

Also the tags for alpha 2 and alpha 1 are again on packagist after a nightly update it seems..

Maybe you can add me as maintainer then I can remove such mistakes my own. Thanks again!

**Comment by ulrichsg** [comment]
There you go :)

**Comment by tflori** [comment]
ahh thanks! 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
