### ISSUE TITLE
required operands and help.

### ISSUE THREAD

**Issue by calguy1000** [getopt-php/getopt-php#83]
When adding a required operand to a command it is impossible to get help for the command because of the error:
Operand NAME is required.

i.e:
```php
$getopt->addOption('h','help');
$cmd = new MyCommand();
$getopt->addCommand( $cmd);

// In class MyCommand:

class MyCommand extends Command
{
     public function __construct() {
         parent::__construct('command',[ $this, 'handle'] );
         $this->addOperand('op1',Operand::REQUIRED);
     }
}
```

to reproduce:
```console
./myapp command --help
```

**Comment by tflori** [comment]
I know this problem. I thought about the same problem when I developed it :smile:

This can only be solved on your end. It's a question of how to implement it:

```php
$getopt->addOption('h','help');
$cmd = new MyCommand();
$getopt->addCommand( $cmd);

try {
  $getopt->process();
} catch (Missing $exception) {
  if (!$getopt->getOption('help')) {
    throw $exception;
  }
}
```

or to show a more complete example how I'm using it:

```php

use GetOpt\GetOpt;

require __DIR__ . '/vendor/autoload.php';

$getopt = new GetOpt([], [
    GetOpt::SETTING_STRICT_OPTIONS => true,
    GetOpt::SETTING_STRICT_OPERANDS => true,
]);

// collect common options
// collect commands

try {
    try {
        $getopt->process();
    } catch (Missing $exception) {
        if (!$getopt->getOption('help')) {
            throw $exception;
        }
    }
} catch (ArgumentException $exception) {
    file_put_contents('php://stderr', $exception->getMessage() . PHP_EOL);
    echo $getopt->getHelpText();
    exit;
}

$command = $getopt->getCommand();
if (!$command || $getopt->getOption('help')) {
    echo $getopt->getHelpText();
} else {
    call_user_func($command->handler());
}
```

**Comment by tflori** [comment]
btw. here is another example in the documentation - but this example will show an error if a command has a required operand that is not provided but help is requested:

http://getopt-php.github.io/getopt-php/example.html

**Comment by tflori** [comment]
## To be more detailed:

### Solution 1: don't throw an exception for missing operands

When GetOpt does not throw an exception because of a missing required operand. The required attribute has no effect at all. 

### Solution 2: don't throw an exception when `--help` is set

This means to restrict the usage of `--help` to show a help text and accept missing required operands, arguments and so on.

> If you have different solutions please let me know. I just had no good idea to overcome this problem on GetOpt side.

**Comment by calguy1000** [comment]
Okay, figured this out.
