### ISSUE TITLE
Improve 3.x backwards-incompatible changes documentation

### ISSUE THREAD

**Issue by dregad** [getopt-php/getopt-php#87]
Hello Thomas,

Today I went through the hoops of upgrading a couple of scripts relying on an older version of GetOpt.PHP for the first time.

It was not a very difficult task, but I think it would be nice to make things a bit more obvious and better documented for other users (currently, the only info I could find is a short [note in the changelog](https://github.com/getopt-php/getopt-php/releases/tag/3.0.0), which is is not enough IMO and also not so easy to find).

I would suggest adding a note in the README file, linking to more details in the documentation.

For the record, here's a list of issues I faced and what I needed to change in my code to get things to work after updating composer.json and downloading the new version:

- Change namespace references - replace `Ulrichsg\Getopt` -> `GetOpt` [changed in 50818ec798a7b3b55e2cecab60193141451a63a6]
- Change base class name - replace `Getopt` -> `GetOpt` [changed in 0b987977ce8c408542bd9eea5b308aaab2626286]
- Remove usage of _setBanner()_ method - this has been replaced by the new Help templates, customize those as needed (see also #88)
- Remove _$padding_ argument in _getHelpText()_ calls [changed in df81d0d2997577a6f754adfa39255fda4c52ecd3]
- Update text passed to _setDescription()_ method - since the new help is automatically wrapping it now

**Comment by tflori** [comment]
Thanks for contributing. I really appreciate it and it's constructive input.

I don't know when I find the time but you are completely right. An update guide will be useful. 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tflori** [comment]
@dregad please have a look at https://github.com/getopt-php/getopt-php/blob/8e92aa398cba33cf3ab779e1525727fd81b5120a/docs/update.md if this is good enough to solve this issue.

**Comment by dregad** [comment]
Thanks for the quick response, your suggestion is quite good, see #90 for proposed improvements.
