### ISSUE TITLE
Improve documentation for Help Text

### ISSUE THREAD

**Issue by dregad** [getopt-php/getopt-php#88]
I find the page at http://getopt-php.github.io/getopt-php/help.html a bit confusing, it's not really clear just reading that and without looking at the code, to understand what has to be done, and how one is supposed to customize things.

**Comment by tflori** [comment]
Without looking at the code it will be hard to understand how to customize the help text. I will have to think more about it..

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tflori** [comment]
@dregad I had a look into the current help and had the same impression :smile:

https://github.com/getopt-php/getopt-php/blob/4283ba7302bd069c9eb48c6b7a8fe859d980d488/docs/help.md

It was describing the the three templates before the customization. I changed this and the texts. How else we could improve this documentation?

**Comment by dregad** [comment]
Thanks for the quick response, I made some suggestions for improvement in #90, and see also #91.
