### ISSUE TITLE
Options with empty string values ignored

### ISSUE THREAD

**Issue by davidbpirie** [getopt-php/getopt-php#93]
I notice that an option with REQUIRED_ARGUMENT can be provided an empty string as a value, but when iterating over the options array this option is skipped. I believe this is because GetOpt ->getIterator() is only returning options where the value evaluates to a true boolean in PHP, and an empty string gets evaluated as false.

Is this intended behaviour? Should the test instead be changed to !is_null()?

**Comment by tflori** [comment]
I think you found a bug. Thanks for your contribution!

**Comment by tflori** [comment]
version 3.0.3 will solve your problem
