### ISSUE TITLE
Does this support positional arguments?

### ISSUE THREAD

**Issue by Bilge** [getopt-php/getopt-php#95]
Sorry for creating an issue for this, but I can't see any reference to positional arguments in the documentation. Positional arguments are those without a leading dash (`-`), which are identified by the position, or order, in which they appear rather than by name. Are positional arguments supported by some mechanism?

**Comment by tflori** [comment]
yes, they are called operands in the documentation. You are right. In other contexts they are often called positional arguments. I will add this term to the readme and documentation. Thanks for your contribution.

http://getopt-php.github.io/getopt-php/operands.html

**Comment by Bilge** [comment]
@tflori Thanks so much for your quick reply! Since this is supported I will try using this library, but I think it's a misnomer to call these *operands*. I believe that in programming, an operand is a value operated on by an operator. In this case there is no operator and therefore they are not operands.

```
  v----- operator
1 + 2
^---^--- operands
```

**Comment by tflori** [comment]
the operator is not always between two operands. for example in reverse polish notation the operator is at the end. in command lines the operand is in the end and the operator is often in front.

```
 v-------------------- operator
cp source destination
      ^----------^---- operands 
```

**Comment by Bilge** [comment]
My point wasn't that an operator must appear in the middle. Indeed, unary operators are often specified like prefixes as in your example. For example unary plus (`+`), e.g. `+'123'`; the operator/operand terminology remains the same. My point was just that you do not have operands at all in this case.

However, I take your counter-point that you can think of positional arguments as operands to the command, or operator, itself. Nevertheless, I have never encountered this terminology used in this manner before and think it would alienate other potential users, too.
